const CARDS = [
  {
    cat: "LIFE",
    icon: "person",
    q: "If money and time were no object, what skill would you master tomorrow?",
    sp: { h: "@aetherlabs", t: "New Era. New Minds." },
  },
  {
    cat: "LIFE",
    icon: "mind",
    q: "If you could change one thing about how you were raised, what would it be?",
    sp: { h: "@aetherlabs", t: "New Era. New Minds." },
  },
  {
    cat: "FAMILY",
    icon: "person",
    q: 'Are you the "responsible one" or the "adventurous one" in your family?',
    sp: { h: "@aetherlabs", t: "New Era. New Minds." },
  },
  {
    cat: "HOBBIES",
    icon: "leaf",
    q: "Do you prefer hobbies that are creative, athletic, or intellectual?",
    sp: { h: "@aetherlabs", t: "New Era. New Minds." },
  },
  {
    cat: "SKILLS",
    icon: "arrow",
    q: "If you had to teach a 30-minute class on any topic, what would it be?",
    sp: { h: "@aetherlabs", t: "New Era. New Minds." },
  },
  {
    cat: "WORK",
    icon: "person",
    q: "What was your very first job, and what did you learn from it?",
    sp: null,
  },
  {
    cat: "FRIENDSHIP",
    icon: "chat",
    q: 'What is a "dealbreaker" for you in a friendship?',
    sp: null,
  },
  {
    cat: "LIFESTYLE",
    icon: "sun",
    q: "If you could retire tomorrow, what would you do with your days?",
    sp: null,
  },
  {
    cat: "ETHICS",
    icon: "split",
    q: "If you find a wallet with $500 and no ID, is it yours?",
    sp: null,
  },
  {
    cat: "TRAVEL",
    icon: "leaf",
    q: "Are you a city sleeper or a nature seeker?",
    sp: null,
  },
  {
    cat: "CAREER",
    icon: "arrow",
    q: "If you could switch careers with anyone for one week, who would it be?",
    sp: null,
  },
  {
    cat: "MINDSET",
    icon: "mind",
    q: 'Does "luck" exist, or do we create our own opportunities?',
    sp: null,
  },
  {
    cat: "TRAVEL",
    icon: "globe",
    q: 'What is the most "culture shock" you’ve ever experienced?',
    sp: null,
  },
  {
    cat: "LIFESTYLE",
    icon: "sun",
    q: "Would you rather live in a high-tech smart home or a cozy cabin in the woods?",
    sp: null,
  },
  {
    cat: "TRAVEL",
    icon: "globe",
    q: "What is the most beautiful place you’ve ever seen in person?",
    sp: null,
  },
  {
    cat: "SCIENCE",
    icon: "split",
    q: "Is it better to explore the deep ocean or outer space?",
    sp: null,
  },
  {
    cat: "ROUTINES",
    icon: "sun",
    q: 'What is your "dream" morning routine?',
    sp: null,
  },
  {
    cat: "ETHICS",
    icon: "mind",
    q: 'Should you report a coworker for a small "theft"? (your coworker is your friend).',
    sp: null,
  },
  {
    cat: "CHILDHOOD",
    icon: "person",
    q: "Are you the child who followed the rules or the one who constantly challenged them?",
    sp: null,
  },
  {
    cat: "FOOD",
    icon: "chat",
    q: 'What is the most iconic "Street Food" spot in the city that everyone must visit once?',
    sp: null,
  },
  {
    cat: "CITY LIFE",
    icon: "sun",
    q: 'What is your favorite "plan" for a Sunday afternoon in the city?',
    sp: null,
  },
  {
    cat: "TRADITIONS",
    icon: "mind",
    q: 'What is a "superstition" your parents or grandparents believe in?',
    sp: null,
  },
  {
    cat: "FAMILY",
    icon: "person",
    q: "What is one tradition you want to make sure you pass down to your children?",
    sp: null,
  },
  {
    cat: "WORK",
    icon: "arrow",
    q: "Do you prefer working for a big company or being your own boss?",
    sp: null,
  },
  {
    cat: "CITY",
    icon: "globe",
    q: "If you were the Mayor for one day, what is the first thing you would fix?",
    sp: null,
  },
  {
    cat: "REMOTE WORK",
    icon: "globe",
    q: 'What is your "dream" remote job that would allow you to travel the world?',
    sp: null,
  },
  {
    cat: "ETHICS",
    icon: "mind",
    q: "Is it ethical to test life-saving medicine on animals?",
    sp: null,
  },
  {
    cat: "SPORTS",
    icon: "arrow",
    q: "If you could be a professional athlete in any sport, which would it be?",
    sp: null,
  },
  {
    cat: "PRODUCTIVITY",
    icon: "mind",
    q: "How do you stay motivated and productive during a power outage or internet failure?",
    sp: null,
  },
  {
    cat: "BUSINESS",
    icon: "arrow",
    q: "If you could open a small business tomorrow, what would you sell?",
    sp: null,
  },
  {
    cat: "ENTERTAINMENT",
    icon: "chat",
    q: 'Do you prefer watching a movie at home or going to the cinema for the "experience"?',
    sp: null,
  },
  {
    cat: "ART",
    icon: "person",
    q: "If you could meet any famous artist (living or dead), who would it be?",
    sp: null,
  },
  {
    cat: "ROUTINES",
    icon: "sun",
    q: 'Are you a "planner" or do you prefer to see where the day takes you?',
    sp: null,
  },
  {
    cat: "TECH",
    icon: "split",
    q: "If you had to delete every app on your phone except for three, which would stay?",
    sp: null,
  },
  {
    cat: "LIFE",
    icon: "mind",
    q: "Is it better to have a life full of stability or a life full of adventure?",
    sp: null,
  },
  {
    cat: "TECH",
    icon: "globe",
    q: "Should there be a legal minimum age for owning a smartphone?",
    sp: null,
  },
];

const ICONS = {
  person: `<svg class="cat-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="8" r="4"/><path d="M4 20c0-4 3.6-7 8-7s8 3 8 7"/></svg>`,
  leaf: `<svg class="cat-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M17 8C8 10 5.9 16.17 3.82 19.37A1 1 0 0 0 4.76 21C12 21 19 15.55 19 8z"/><path d="M17 8l-1.36 8.17"/></svg>`,
  sun: `<svg class="cat-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M4.93 4.93l1.41 1.41m11.32 11.32 1.41 1.41M2 12h2m16 0h2M4.93 19.07l1.41-1.41M18.66 5.34l1.41-1.41"/></svg>`,
  split: `<svg class="cat-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><circle cx="18" cy="5" r="2"/><circle cx="18" cy="19" r="2"/><circle cx="6" cy="12" r="2"/><line x1="8" y1="12" x2="16" y2="5"/><line x1="8" y1="12" x2="16" y2="19"/></svg>`,
  chat: `<svg class="cat-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"/></svg>`,
  globe: `<svg class="cat-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><circle cx="12" cy="12" r="10"/><line x1="2" y1="12" x2="22" y2="12"/><path d="M12 2a15.3 15.3 0 0 1 4 10 15.3 15.3 0 0 1-4 10 15.3 15.3 0 0 1-4-10 15.3 15.3 0 0 1 4-10z"/></svg>`,
  arrow: `<svg class="cat-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><line x1="12" y1="19" x2="12" y2="5"/><polyline points="5 12 12 5 19 12"/></svg>`,
  mind: `<svg class="cat-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M9.5 2A2.5 2.5 0 0 1 12 4.5v15a2.5 2.5 0 0 1-4.96-.46 2.5 2.5 0 0 1-1.07-4.6A3 3 0 1 1 9.5 2Z"/><path d="M14.5 2A2.5 2.5 0 0 0 12 4.5v15a2.5 2.5 0 0 0 4.96-.46 2.5 2.5 0 0 0 1.07-4.6A3 3 0 1 0 14.5 2Z"/></svg>`,
};

const CUP = `<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M18 8h1a4 4 0 0 1 0 8h-1"/><path d="M2 8h16v9a4 4 0 0 1-4 4H6a4 4 0 0 1-4-4V8z"/><line x1="6" y1="1" x2="6" y2="4"/><line x1="10" y1="1" x2="10" y2="4"/><line x1="14" y1="1" x2="14" y2="4"/></svg>`;
